name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name "*.py" | xargs)
