name: Pylint

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
  schedule:
    - cron: '0 5 * * 1' # Every Monday at 05:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5.2.0
      with:
        python-version: 3.14
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Analysing the code with pylint
      run: |
        pylint $(find . -name "*.py" | xargs)
